<script lang="ts">
	// @ts-nocheck
	import { routes } from "./router";
	import logo from "/src/assets/logo.svg";
	import title from "./assets/title.svg";
	import language from "/src/assets/language.svg";
	import Router, { location, push } from "svelte-spa-router";
	import cx from "clsx";
	import { slide, fly } from "svelte/transition";
	import menu from "./assets/menu.svg";
	import { onDestroy, onMount } from "svelte";
	import { getInfo } from "./requests/user/getInfo";
	import { userInfo } from "./stores/userInfo";
	import { Message } from "./utils/Message";
	import { recruitment } from "./stores/recruitment";
	import { getLatestRecruitment } from "./requests/recruitment/getLatest";
	import Groups from "./icons/Groups.svelte";
	import { latestInfo } from "./stores/latestApplication";
	import { LANGUAGES } from "./config/const";
	import { localeLanguage } from "./stores/localeLanguage";
	import { t } from "./utils/t";
	import { i18nConstants } from "./config/i18n";
	import SideBar from "./components/history/SideBar.svelte";
	// import { isMobile } from "./stores/isMobile";
	import font from "figlet/importable-fonts/3D-ASCII";
	import figlet from "figlet";
	import chalk from "chalk";
	import { drawFireWork } from "./utils/firework";
	import { getDepartments } from "./requests/config/getDepartments";
	import { departments } from "./stores/departments";
	import { parseDepartments } from "./utils/parseDepartments";
	import { globalLoading } from "./stores/globalLoading";
	import { editMode } from "./stores/editMode";

	let canvas = document.createElement("canvas");
	let deleted = false;
	const easterEgg = (e: KeyboardEvent) => {
		if (e.shiftKey && e.ctrlKey && e.code === "KeyU") {
			drawFireWork(canvas, deleted);
			deleted = !deleted;
		}
	};

	figlet.parseFont("3d", font);
	figlet
		.text("Unique Studio", { font: "3d" }, () => {})
		.then((text: string) => {
			console.log(
				chalk.cyan(text) +
					"\n" +
					chalk.blue("听说按下 ctrl + shift + u 会有神奇的事发生~") +
					"\n" +
					chalk.yellow("developed by Unique Web ") +
					chalk.green("@HUST-SE-LY @willburwwb @yqaty @Yuukirn")
			);
		});

	let showAvatarDetail = false;
	let showLanguageSelector = false;
	let home: HTMLDivElement;
	let user: HTMLDivElement;
	let tabLine: HTMLDivElement;
	let hideTopBar = false;
	let lastScrollTop = 0;
	let hide = true;
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	let isLoading = false;

	const doc = document.documentElement;
	//ly: generated by gpt3.5 :)
	const handleScroll = () => {
		const scrollTop = (window.pageYOffset || doc.scrollTop) - (doc.clientTop || 0);
		if (scrollTop > lastScrollTop) {
			hideTopBar = true;
		} else {
			hideTopBar = false;
		}
		lastScrollTop = scrollTop <= 0 ? 0 : scrollTop;
	};
	const i18nKeys = Object.keys(i18nConstants) as (keyof typeof i18nConstants)[];
	if (!($userInfo && $latestInfo)) {
		getInfo()
			.then((res) => {
				userInfo.setInfo(res.data);
				// 删除 $latestInfo 可能对本地有影响，但没有问题
				// 旨在解决更换账号数据不更新的问题
				if (
					$recruitment &&
					$recruitment.uid === $userInfo.applications[0]?.recruitment_id &&
					res.data.applications[0]
				) {
					// if (!$latestInfo && res.data.applications[0]) {
					latestInfo.setApplication(res.data);
				} else if (!$latestInfo?.qq_account && res.data.qq_account) {
					// ly: if qq_account is added to backend but not in localStorage, valid it
					latestInfo.updateInfo({
						groups: $latestInfo?.groups || [],
						qq_account: res.data.qq_account
						// eslint-disable-next-line @typescript-eslint/no-explicit-any
					} as any);
				}
			})
			.catch((err) => {
				if (err.message === "authentication failed could not get uid") {
					return;
				}
				Message.error($t("header.getInfoFailed"));
			})
			.finally(() => {
				isLoading = false;
			});
	}
	if (!$recruitment)
		getLatestRecruitment()
			.then((res) => {
				recruitment.setRecruitments(res.data);
			})
			.catch((err) => {
				if (
					err.message === "authentication failed could not get uid" ||
					err.message === `ERROR: invalid input syntax for type uuid: \\"\\" (SQLSTATE 22P02)`
				) {
					return;
				}
				Message.error($t("header.getInfoFailed"));
			});

	if (!$departments.length)
		getDepartments()
			.then((resp) => parseDepartments(resp.data.nodes))
			.then((resp) => {
				const keys = Object.keys(resp);
				if (keys.length <= 10) {
					throw Error("专业个数过少");
				}
				const firstKey = keys[0];
				if (typeof firstKey !== "string") {
					throw Error("firstKey 应为 string");
				}
				if (!Array.isArray(resp[firstKey])) {
					throw Error("元素不为数组");
				}
				return resp;
			})
			.catch(async (e: Error) => {
				console.error("解析 飞书 专业列表报错：", e.message, "进入fallback");
				// 动态导入
				return (await import("./config/DEPARTMENTS")).default;
			})
			.then(departments.setDepartments);

	const handleRouterClick = (path: string) => {
		if ($editMode) {
			Message.warning("请先退出编辑模式，以防数据丢失");
			return;
		}

		push(path);
	};
	const unsubscribeLocaleLanguage = localeLanguage.subscribe(() => {
		if (tabLine && user && home) {
			Promise.resolve().then(() => {
				tabLine.style.width = `${$location === "/user" ? user.clientWidth : home.clientWidth}px`;
				tabLine.style.transform =
					$location === "/user" ? `translateX(${home.clientWidth + 32}px)` : `translateX(0px)`;
			});
		}
	});
	const unsubscribeLocation = location.subscribe(() => {
		if (tabLine && user && home) {
			Promise.resolve().then(() => {
				tabLine.style.width = `${$location === "/user" ? user.clientWidth : home.clientWidth}px`;
				tabLine.style.transform =
					$location === "/user" ? `translateX(${home.clientWidth + 32}px)` : `translateX(0px)`;
			});
		}
	});
	onMount(() => {
		window.addEventListener("scroll", handleScroll, false);
		window.addEventListener("keydown", easterEgg);
		tabLine.style.width = `${$location === "/user" ? user.clientWidth : home.clientWidth}px`;
		tabLine.style.transform =
			$location === "/user" ? `translateX(${home.clientWidth + 32}px)` : `translateX(0px)`;
	});

	onDestroy(() => {
		unsubscribeLocaleLanguage();
		unsubscribeLocation();
		window.removeEventListener("scroll", handleScroll);
		window.removeEventListener("keydown", easterEgg);
	});
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<!-- svelte-ignore a11y-no-static-element-interactions -->
<div class="h-full min-h-screen overflow-scroll bg-[rgba(0,0,0,0.04)] sm:pt-[6rem]">
	<div
		class={cx([
			"left-0 top-0 z-20 h-[5rem] w-full bg-[rgba(49,84,174,0.58)] px-[4rem] py-[0.5rem] transition-all duration-700 max-lg:px-[3rem] max-md:px-[1rem] max-sm:flex max-sm:bg-[#315ED0] sm:fixed sm:grid sm:grid-cols-3",
			hideTopBar ? "translate-y-[-5rem]" : "translate-y-0"
		])}
	>
		<!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
		<img src={menu} alt="menu" on:click={() => (hide = false)} class="self-center sm:hidden" />
		<a class="flex-shrink-0 self-end max-sm:hidden" href="https://hustunique.com" target="_blank">
			<div class="flex items-center gap-[0.5rem]">
				<img draggable={false} src={logo} alt="UniqueStudio" />
				<p class="mb-[0.5rem] text-lg text-white">{$t("header.team")}</p>
			</div>
		</a>
		<div class="flex w-full justify-center sm:hidden">
			<img src={title} alt="联创招新" class="mx-auto h-[22px] flex-shrink-0 self-center" />
		</div>
		<div
			class="relative flex flex-shrink-0 gap-[2rem] self-center justify-self-center text-white max-sm:hidden"
		>
			<div bind:this={home} class="cursor-pointer" on:click={() => handleRouterClick("/")}>
				{$t("header.applications")}
			</div>
			<div bind:this={user} class="cursor-pointer" on:click={() => handleRouterClick("/user")}>
				{$t("header.info")}
			</div>
			<div
				bind:this={tabLine}
				class={cx(["absolute bottom-[-0.5rem] h-[3px] rounded-full bg-white transition-all"])}
			/>
		</div>
		{#if $userInfo}
			<div
				class="relative ml-auto flex flex-shrink-0 select-none items-center self-center sm:mr-[2rem] sm:gap-[24px]"
			>
				<div>
					<!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
					<img
						on:click={() => (showLanguageSelector = !showLanguageSelector)}
						alt="language"
						class="h-[24px] w-[24px] cursor-pointer max-sm:hidden"
						src={language}
					/>
					{#if showLanguageSelector}
						<div
							transition:slide
							class="absolute right-[64px] top-[48px] z-[999] w-[149px] rounded-[6px] bg-white py-[6px]"
						>
							{#each i18nKeys as key (key)}
								<button
									on:click={() => {
										showLanguageSelector = false;
										localeLanguage.updateLanguage(key);
									}}
									class="h-[46px] w-full text-center leading-[46px] hover:bg-gray-150 max-md:h-[32px] max-md:leading-[32px]"
									>{LANGUAGES[key]}</button
								>
							{/each}
						</div>
					{/if}
				</div>
				<div class="relative">
					<div
						on:click={() => (showAvatarDetail = !showAvatarDetail)}
						class=" h-[40px] w-[40px] cursor-pointer rounded-full bg-white text-center leading-[40px] text-text-3 max-sm:h-[32px] max-sm:w-[32px] max-sm:text-[12px] max-sm:leading-[32px]"
					>
						{$userInfo.name[0]}
					</div>
					{#if showAvatarDetail}
						<div
							transition:slide
							class="absolute right-0 top-[48px] w-[149px] rounded-[6px] bg-white py-[6px]"
						>
							<button
								on:click={() => (window.location.href = "https://sso2024.hustunique.com/")}
								class="h-[46px] w-full text-center leading-[46px] hover:bg-gray-150 max-md:h-[32px] max-md:leading-[32px]"
								>{$t("header.accountManagement")}</button
							>
							<button
								on:click={() =>
									(window.location.href =
										"https://sso2024.hustunique.com/login?logout=true&from=join2024.hustunique.com")}
								class="h-[46px] w-full text-center leading-[46px] text-red-warning hover:bg-gray-150 max-md:h-[32px] max-md:leading-[32px]"
								>{$t("header.logout")}</button
							>
						</div>
					{/if}
				</div>
			</div>
		{/if}
	</div>
	<div
		class="fixed left-0 top-0 -z-10 h-[15rem] w-full overflow-hidden bg-[rgba(53,100,221,1)] max-sm:invisible"
	>
		<Groups />
	</div>
	<div class="h-[80px] w-full sm:hidden"></div>
	<Router {routes} />
</div>

{#if $globalLoading}
	<div class="fixed inset-0 z-[100] flex items-center justify-center bg-white/20">
		<div
			transition:fly={{ y: 20, duration: 300 }}
			class="shadow-2xl flex flex-col items-center gap-4 rounded-xl border border-gray-100 bg-white p-8"
		>
			<div
				class="h-10 w-10 animate-spin rounded-full border-4 border-blue-400 border-t-transparent"
			></div>
			<p class="text-gray-700 text-base font-medium">
				{$t("header.loading")}
			</p>
		</div>
	</div>
{/if}

<div class="sm:hidden">
	<SideBar {hide} on:hide={() => (hide = true)} />
</div>

<style>
	@font-face {
		font-family: "PingFang";
		src: url("/PingFangSC-Regular.woff2");
	}

	* {
		font-family: "PingFang", sans-serif;
	}
</style>
